### PR TITLE
TEIIDWEBCN-47: adding an parameter to the list-vdbs call not to inclu…

### PR DESCRIPTION
**Pull request by rareddy**
…de to fetch ddl

### CODE REVIEW

**Comment by johnathonlee** [comment]
@vhalbert Can you accept this PR?  I don't appear to have rights... but would have sworn I had done so before.

**Comment by vhalbert** [comment]
@johnathonlee I don't have rights either.

**Comment by rareddy** [comment]
@johnathonlee I do but since we closed the ticket already this may not be required, so we can close it. If we want to do it either case for future, then there is supporting Teiid commit is required too.

**Comment by johnathonlee** [comment]
@rareddy the reason I'm looking at it and the related Teiid jira as they've been identified for backport for 6.4.4.  So,  if you can commit please do so.

**Comment by rareddy** [comment]
@johnathonlee done.

**Pull request merged**
