### PR TITLE
TEIIDWEBCN-19 upgrading web console to 2.5.6.Final to match the latest EAP 6.4.2

### PR DESCRIPTION
**Pull request by vhalbert**

### CODE REVIEW

**Comment by rareddy** [comment]
You have to update Teiid versions to match their numbers as they had a build issue with that

**Comment by vhalbert** [comment]
Interesting, because, looking at the product build, they substituted for the 2.5.6.Final-redhat-1 for jboss-as, but didn't change teiid-webconsole, example:

DEBUG util.py:257:  [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ teiid-console-dist ---
DEBUG util.py:257:  [INFO] Building jar: /maven/build/teiid-web-console/dist/target/teiid-console-dist-2.5.5.Final-redhat-4.jar

For which this was included in the hal build.   Could that have been causing the subsequent issue when being using in EAP?

**Comment by rareddy** [comment]
I am not sure about the HAL build, but for me to build locally these need to be in exactly same

**Comment by vhalbert** [comment]
Interesting, I successfully rebuilt without that those versions matching.

**Comment by rareddy** [comment]
The reason is both versions are available in the Maven repo as per building, but it was to generate code I am not sure what will be the effects

**Comment by vhalbert** [comment]
Ok, made the teiid version match the jboss version

**Comment by rareddy** [comment]
merged

**Pull request merged**
