### PR TITLE
TEIIDWEBCN-34: Some bugs about Unknown attribute

### PR DESCRIPTION
**Pull request by JieRenRH**
Because 32&33 issues are quit easy, so I combine these two issues into one pull request with 34.
1.TEIIDWEBCN-34:Some bugs about Unknown attribute
 a.Add new tab named Authentication.
 b.Modify Transport ,remove some options and add input/output-buffer-size options.
2.TEIIDWEBCN-33:A bug about  Teiid configuration setting(Distributed Cache)
 Remove the distributed-cache-channel in SubsystemConfiguration.java and Web UI
3.TEIIDWEBCN-32: A bug about Teiid configuration setting(Buffer Manager)
Remove buffer-service-connector-batch-size and keep the "buffer-service-processor-batch-size"

### CODE REVIEW

**Comment by rareddy** [comment]
I need to see what has changed, but in your commit I see who files have been deleted and added back with totally different format, which obscures what the change you made. So, I need to go go back not reformat the file but edit the required places so I can clearly see what has been changed. The culprits are SubsystemPresenter.java , SubsystemView, TransportEditor. Also when you providing the pull request try flatten your commits into single commit.

**Comment by kylinsoong** [comment]
@JieRenRH I think it should be better not wrap multiple issues in one pull request, it increase the complexity of reviewing.

**Comment by SnailJie** [comment]
Oh,I am so sorry, I have realized my mistake, I promise it will not happen again. I will commit issues one by one so that you can check code clearly. I'm sorry for the trouble I caused you.

**Comment by rareddy** [comment]
no problem, correct and submit new one

**Pull request closed without merging**
